export const cardData = [
    {
      id: "product-1",
      name: "EggPlant",
      imgName: "EggPlant",
      title: "Healthy Food",
      details: "A hamburger (also burger for short) is a sandwich consisting of one or more cooked patties of ground meat, usually beef, placed inside a sliced bread Read More...",
      calori: "58 cal/100 g ",
      foodSearch: "blue",
      category: "Vegetables",
    },
    {
      id: "product-2",
      name: "Tomato",
      imgName: "Tomato",
      title: "Healthy Food",
      details:
        "A hamburger (also burger for short) is a sandwich consisting of one or more cooked patties of ground meat, usually beef, placed inside a sliced bread Read More... ",
      calori: "58 cal/100 g ",
      foodSearch: "red",
      category: "Vegetables",
    },
    {
      id: "product-3",
      name: "Banana",
      imgName: "Banana",
      title: "Healthy Food",
      details:
        "A hamburger (also burger for short) is a sandwich consisting of one or more cooked patties of ground meat, usually beef, placed inside a sliced bread Read More... ",
      calori: "58 cal/100 g ",
      foodSearch: "yellow",
      category: "Fruits",
    },
    {
      id: "product-4",
      name: "Cabbage",
      imgName: "Cabbage",
      title: "Healthy Food",
      details:
        "A hamburger (also burger for short) is a sandwich consisting of one or more cooked patties of ground meat, usually beef, placed inside a sliced bread Read More... ",
      calori: "58 cal/100 g ",
      foodSearch: "green",
      category: "Vegetables",
    },
    {
      id: "product-5",
      name: "Potato",
      imgName: "Potato",
      title: "Healthy Food",
      details:"A hamburger (also burger for short) is a sandwich consisting of one or more cooked patties of ground meat, usually beef, placed inside a sliced bread Read More... ",
      calori: "58 cal/100 g ",
      foodSearch: "brown",
      category: "Vegetables",
    },
    {
      id: "product-6",
      name: "Lettuce",
      imgName: "Lettuce",
      title: "Healthy Food",
      details:"A hamburger (also burger for short) is a sandwich consisting of one or more cooked patties of ground meat, usually beef, placed inside a sliced bread Read More... ",
      calori: "58 cal/100 g ",
      foodSearch: "green",
      category: "Vegetables",
    },
  ];